# .travis.yml
language:
  - python
python:
  - "3.6.8"
  - "2.7"
cache:
  - pip3

# getting dependencies
install:
  - "pip3 install -r requirements.txt"

script:
  - nosetests
after_success:
  - coveralls
