# .travis.yml
language:
  - python
python:
  - "2.7"
cache:
  - pip

# getting dependencies
install:
  - "pip install -r requirements.txt"

script:
  - nosetests -v app/my_api/tests/v1
after_success:
  - coveralls
