# .travis.yml
language:
  - python
python:
  - "2.7"
cache:
  - pip

# getting dependencies
install:
  - "pip install -r requirements.txt"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nosetests -v app/my_api/tests/v1

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls
