# .travis.yml
language:
  - python
python:
  - "2.7"
cache:
  - pip

# getting dependencies
install:
  - "pip install -r requirements.txt"

env:
  - export CODECOV_TOKEN="f6586b45-c8c8-4d13-86cd-586543bed541"
  global:
    - CC_TEST_REPORTER_ID=c4161de17790461d95283922109d0a07efcfd29f35e824b4cac8fbc1d0f9aa86

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nosetests -v app/my_api/tests/v1 --with-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls
